sudo: false

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - gettext

before_script: 
- mvn -N io.takari:maven:0.4.3:wrapper -Dmaven=3.5.0
- xgettext --version

script: 
- ./mvnw clean package source:jar javadoc:jar install
